#!/bin/bash -ex
#
# Build AWS Lambda function ZIP file and upload to S3
#
# Usage: ./build-upload-aws-lambda-function S3BUCKET S3REGION S3KEY [HUGOVERSION]
#
# For example:
# ./build-upload-aws-lambda-function run.alestic.com us-west-1 lambda/aws-lambda-site-generator-hugo-0.17.zip 0.17
#

s3bucket=${1:?Specify target S3 bucket name}
s3region=${2:?Specify target S3 region}
s3key=${3:?Specify target S3 key}
target=s3://$s3bucket/$s3key
hugo_version="${4:-0.20}"

tmpdir=$(mktemp -d /tmp/lambda-XXXXXX)
zipfile=$tmpdir/lambda.zip

# Add AWS Lambda function file to ZIP file
zip -r9 $zipfile index.py

# Download and add Hugo binary executable to ZIP file
download_url="https://github.com/spf13/hugo/releases/download/"
if [[ "0.14" == $hugo_version ]] ; then
  download_url="${download_url}v0.14/hugo_0.14_linux_amd64.tar.gz"
fi
if [[ "0.15" == $hugo_version ]] ; then
  download_url="${download_url}v0.15/hugo_0.15_linux_amd64.tar.gz"
fi
if [[ "0.16" == $hugo_version ]] ; then
  download_url="${download_url}v0.16/hugo_0.16_linux-64bit.tgz"
fi
if [[ "0.17" == $hugo_version ]] ; then
  download_url="${download_url}v0.17/hugo_0.17_Linux-64bit.tar.gz"
fi
if [[ "0.18" == $hugo_version ]] ; then
  download_url="${download_url}v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz"
fi
if [[ "0.19" == $hugo_version ]] ; then
  download_url="${download_url}v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz"
fi
if [[ "0.20" == $hugo_version ]] ; then
  download_url="${download_url}v0.20.6/hugo_0.20.6_Linux-64bit.tar.gz"
fi
(
 cd $tmpdir
 wget -qO hugo.tar.gz $download_url
 tar xvzf hugo.tar.gz
 mv hugo_${hugo_version}*/hugo_${version}* ./hugo
 zip -r9 $zipfile hugo
)

# Upload AWS Lambda function ZIP file to S3
aws s3 cp --acl public-read $zipfile $target --region $s3region

# Clean up
rm -r $tmpdir
